; DriveBackup installer - generated by build.py (do not edit manually)
; #define placeholders replaced at build time.

#define MyAppName "DriveBackup"
#define MyAppVersion "__VERSION__"
#define MyAppExeName "DriveBackup.exe"

[Setup]
AppId={{2E1B8A84-9D3F-4C2A-B5C7-3F9E2D0A6C41}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher=DriveBackup
DefaultDirName={localappdata}\DriveBackup
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
OutputDir=dist
OutputBaseFilename=DriveBackup-Setup-{#MyAppVersion}
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
UninstallDisplayIcon={app}\{#MyAppExeName}
CloseApplications=yes
RestartApplications=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; ignoreversion => files are replaced in place on update (no uninstall needed)
Source: "dist\DriveBackup\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\DriveBackup"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\DriveBackup"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,DriveBackup}"; Flags: nowait postinstall skipifsilent