from datetime import datetime
from typing import Any, Dict, List, Optional

from ..utils.config import format_bytes, report_path


def _table(headers: List[str], rows: List[List[Any]]) -> str:
    lines = ["| " + " | ".join(headers) + " |",
             "|" + "|".join(["---"] * len(headers)) + "|"]
    for row in rows:
        lines.append("| " + " | ".join(str(c) for c in row) + " |")
    return "\n".join(lines)


def generate_report(backup: Optional[dict[str, Any]] = None,
                    verify: Optional[dict[str, Any]] = None,
                    analysis: Optional[dict[str, Any]] = None,
                    plan: Optional[List[dict[str, Any]]] = None,
                    llm_summary: Optional[str] = None,
                    ai_findings: Optional[List[dict[str, str]]] = None) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    out: List[str] = []
    out.append(f"# Drive Backup Report\n\nGenerated: {now}\n")

    if backup:
        out.append("## Backup\n")
        out.append(_table(
            ["Metric", "Value"],
            [["Files", backup.get("files", 0)],
             ["Total size", format_bytes(backup.get("bytes", 0))],
             ["Files on local disk", backup.get("local_files", 0)],
             ["Matched", backup.get("ok", 0)],
             ["Missing", backup.get("missing", 0)]]))

    if verify:
        out.append("\n## Integrity Verification\n")
        status = "PASS" if verify.get("passed") else "FAIL"
        out.append(_table(
            ["Metric", "Value"],
            [["Status", status],
             ["Verified at", verify.get("created", "")],
             ["Total", verify.get("total", 0)],
             ["OK", verify.get("matched", 0)],
             ["Missing", verify.get("missing", 0)],
             ["Mismatched", verify.get("mismatch", 0)],
             ["Extra local files", verify.get("extra", 0)]]))
        if not verify.get("passed"):
            bad = [r for r in verify.get("results", [])
                   if r["status"] not in ("OK", "OK (exported)")]
            out.append("\n### Issues\n")
            out.append(_table(["Path", "Issue"], [(r["path"], r["status"]) for r in bad[:200]]))

    if analysis:
        a = analysis
        out.append("\n## Drive Analysis\n")
        out.append(_table(
            ["Category", "Files", "Size"],
            [[k, v["count"], format_bytes(v["size"])]
             for k, v in sorted(a["categories"].items(), key=lambda kv: -kv[1]["size"])]))
        out.append(f"\n- **Duplicates:** {a['dup_count']} groups, "
                   f"**{format_bytes(a['dup_wasted'])}** wasted")
        out.append(f"- **Junk files:** {format_bytes(a['junk_size'])} "
                   f"across {len(a['junk'])} junk categories")
        out.append(f"- **Empty files:** {len(a['empty_files'])}")
        if a["top_files"]:
            out.append("\n### Largest files\n")
            out.append(_table(["Path", "Size"], [
                [f["path"], format_bytes(f["size"])] for f in a["top_files"][:20]]))

    if plan:
        out.append("\n## Suggested Organization\n")
        cats: Dict[str, dict[str, Any]] = {}
        for entry in plan:
            cats.setdefault(entry["category"], {"count": 0, "target": entry["target"]})
            cats[entry["category"]]["count"] += 1
        out.append(_table(["Category", "Files", "Example target"],
                          [[k, v["count"], v["target"]] for k, v in cats.items()]))

    if llm_summary:
        out.append("\n## AI Executive Summary\n")
        out.append(llm_summary)

    if ai_findings:
        out.append("\n## AI Findings\n")
        for f in ai_findings:
            out.append(f"- **{f['severity'].upper()}:** {f['message']}")

    out.append("\n---\n*Generated by Drive Backup Tool*")
    return "\n".join(out)


def save_report(content: str) -> str:
    path = report_path(f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md")
    path.write_text(content, encoding="utf-8")
    return str(path)
